### PR TITLE
Upgrade travis golang to 1.10

### PR DESCRIPTION
**Pull request by adambkaplan**
Required for latest s2i changes.

/assign @bparees

### CODE REVIEW

**Comment by bparees** [comment]
```
$ hack/build-go.sh
++ Building go targets for linux/amd64: cmd/s2i
flag provided but not defined: -pkgdir
usage: install [build flags] [packages]
```

**Comment by bparees** [comment]
```
$ go version
go version go1.1 linux/amd64
go.env
$ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.1.src"
GOTOOLDIR="/home/travis/.gimme/versions/go1.1.src/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CGO_ENABLED="1"
before_install.1
0.00s$ pushd /tmp
/tmp ~/gopath/src/github.com/openshift-s2i/s2i-wildfly
before_install.2
2.52s$ git clone https://github.com/openshift/source-to-image source-to-image
Cloning into 'source-to-image'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 25064 (delta 3), reused 15 (delta 3), pack-reused 25041
Receiving objects: 100% (25064/25064), 22.73 MiB | 20.93 MiB/s, done.
Resolving deltas: 100% (10211/10211), done.
before_install.3
0.00s$ cd source-to-image
0.33s$ hack/build-go.sh
++ Building go targets for linux/amd64: cmd/s2i
flag provided but not defined: -pkgdir
usage: install [build flags] [packages]
```

**Comment by bparees** [comment]
looks like you got golang v1.1 somehow....

**Comment by adambkaplan** [comment]
uggh YAML - think it parsed 1.10 to the number 1.1. Should be fixed now.

**Pull request merged**
