### PR TITLE
Update postgresql driver to 9.4.1211

### PR DESCRIPTION
**Pull request by adrianbader**
Update postgresql driver for every Wildfly version to 9.4.1211.
...it's my first PR; hope it works :)
Thanks integrating it and rebuild/push docker image!

fixes https://github.com/openshift-s2i/s2i-wildfly/issues/137

### CODE REVIEW

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by bparees** [comment]
@dobbymoodge test pull requests is broken for this repo:
https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_wildfly_images/4/console

```
/bin/test_pull_requests:1152:in `[]': no implicit conversion of Symbol into Integer (TypeError)
	from /bin/test_pull_requests:1152:in `block in get_comment_matching_regex'
	from /var/lib/jenkins/.gem/ruby/gems/sawyer-0.8.1/lib/sawyer/resource.rb:123:in `each'
	from /var/lib/jenkins/.gem/ruby/gems/sawyer-0.8.1/lib/sawyer/resource.rb:123:in `each'
	from /bin/test_pull_requests:1152:in `select'
	from /bin/test_pull_requests:1152:in `get_comment_matching_regex'
	from /bin/test_pull_requests:1159:in `get_comment_with_prefix'
	from /bin/test_pull_requests:967:in `test_merge_pull_request'
	from /bin/test_pull_requests:892:in `merge_pull_request'
	from /bin/test_pull_requests:2428:in `<main>'
```

can you take a look?

**Comment by adrianbader** [comment]
Hmm, I actually do not fully understand, what is going on in this test and what exactly fails...

**Comment by bparees** [comment]
@adrianbader it's related to our CI system, the PR itself is fine, we'll get it merged after we fix up the CI system.

**Comment by bparees** [comment]
[test]

**Pull request merged**
