### PR TITLE
Fix #163 jboss-cli local authentication does not work on OpenShift

### LINKED ISSUE #163: jboss-cli local authentication does not work on OpenShift
This is caused by the fact that the root group cannot access `/wildfly/standalone/tmp/auth`. It is solvable by adding `X` to the existing `chmod -R ug+rw /wildfly` thus changing it to `chmod -R ug+rwX /wildfly`. 

A PR follows

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by bparees** [comment]
thanks @ppalaga 

/lgtm

**Comment by kargakis** [comment]
@bparees @stevekuznetsov `openshift-merge-robot` is not authorized to merge PRs in this repo.
```
{"base-sha":"152b269d8b9b448f034bc6db1a92e139c0b5cdfd","branch":"master","component":"tide","controller":"sync","error":"You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.","level":"error","msg":"Merge failed: PR is unmergable. How did it pass tests?!","org":"openshift-s2i","pr":164,"repo":"s2i-wildfly","sha":"d5cadfc6f8f4b59947dfd0187f2d97d384fbf577","time":"2018-03-28T10:52:20Z"}
```

**Comment by bparees** [comment]
@kargakis merge-bot and ci-bot are both listed as collaborators w/ write access.

Since we have branch protection on, perhaps something additional is needed, but it's the same setup we have in our other repos?

**Comment by bparees** [comment]
ok I may have fixed it.

/retest

**Comment by bparees** [comment]
i guess i did. :)

thanks @kargakis

**Pull request merged**
