### PR TITLE
chmod/chgrp artifacts before moving them

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@jorgemoralespou ptal.  we ultimately want the files in the deployments dir to be writable, so don't we either need to chmod the files before moving them, or chmod the destination dir?

this was moving the files and then chmod'ing the old location (which wouldn't even exist anymore)

**Comment by jorgemoralespou** [comment]
@bparees what about 8.1 and 9?
Else lgtm

**Comment by bparees** [comment]
> @bparees what about 8.1 and 9?

"deprecated"

**Comment by jorgemoralespou** [comment]
@bparees I guess you've deprecated them in the imagestreams we ship in origin. Wouldn't it be also nice to say so in the README that they are no longer maintained and deprecated?

**Comment by bparees** [comment]
i haven't.  this is all "as i have time" stuff, ensuring people know the wildfly 8.1 image is deprecated doesn't rise to a high enough priority for me to spend time on it.

**Comment by bparees** [comment]
[test]

**Pull request merged**
