### PR TITLE
Add Jenkins build status badge

### PR DESCRIPTION
**Pull request by jawnsy**
Signed-off-by: Jonathan Yu <jawnsy@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
That's going to reflect the status of the last pull that was tested. Doesn't make sense as the repo (master) status.

**Comment by jawnsy** [comment]
@bparees Ah! How do we make it reflect master? I think it'd be useful to make the Jenkins build more discoverable (at least it would've been beneficial for me)

**Comment by mfojtik** [comment]
We do not build the master after push, but assuming every PR is tested, the
master will always be green.
We can link to the PR tester job but I dont think it makes too much
sense.... The link to that job is available under every PR.

**Comment by bparees** [comment]
we don't have a job that explicitly tests master for just this repo.  The push images job is the one that builds master (and pushes it to dockerhub when successful), but that builds many different images, not just this one.

**Comment by jawnsy** [comment]
Closing since we don't have a Jenkins build for master, and it wouldn't make much sense to show build results for PRs.

**Pull request closed without merging**
