### PR TITLE
setup openshift default datasource env var properly

### PR DESCRIPTION
**Pull request by bparees**
fixes https://github.com/openshift-s2i/s2i-wildfly/issues/128

### CODE REVIEW

**Comment by bparees** [comment]
@Larzenegger ptal, i think this is the right fix.  We do pre-processing on the standalone.xml because wildfly doesn't support env var references itself.  the pre-processing only looks for env.OPENSHIFT_* refernces in the standalone.xml file.

**Comment by Larzenegger** [comment]
I'm afraid this still returns the following bind message when running the Wildfly 8.1 container:
> Bound data source [java:jboss/datasources/${env.EXAMPLE_DATASOURCE}]

And therefore the deployment afterwards fails with the message:
> missing/unavailable dependencies: (...).DefaultDataSource is missing [jboss.naming.context.java.jboss.datasources.ExampleDS]

**Comment by bparees** [comment]
you sure you built/ran my latest commit?  I don't see that message and env.EXAMPLE_DATASOURCE no longer appears in the standalone.xml at all:
https://github.com/bparees/sti-wildfly/blob/732ac60e0f0a3c00447dff1d6706a99c56357dea/8.1/contrib/wfcfg/standalone.xml

**Comment by Larzenegger** [comment]
Apologies for the confusion, it seems I mixed up a few things.

I now managed to fetch & check out your pull request and rebuild my openshift/wildfly-81-centos7 image. Used it to s2i build and run the example project. Encountered no error.

Thank you!

**Comment by bparees** [comment]
Great, thanks for the feedback!

**Pull request merged**
