### PR TITLE
Reference correct schema versions for WildFly 10.1.0.Final

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by bparees** [comment]
[test]

**Comment by bparees** [comment]
thanks @jamesnetherton!

**Comment by jamesnetherton** [comment]
@bparees Thanks for merging - does the image get automatically rebuilt and pushed to Docker Hub?

**Comment by bparees** [comment]
@jamesnetherton yeah, within an hour or so.

**Pull request merged**
